plugins:
  - rubocop-factory_bot
  - rubocop-performance
  - rubocop-rails
  - rubocop-rspec
  - rubocop-rspec_rails

AllCops:
  DefaultFormatter: progress
  DisplayCopNames: true
  ExtraDetails: true
  NewCops: enable
  SuggestExtensions: false
  TargetRubyVersion: 3.2
  Exclude:
    - "bin/*"
    - "vendor/**/*"
    - "spec/dummy/db/schema.rb"

FactoryBot/FactoryAssociationWithStrategy:
  Enabled: false

Layout/AccessModifierIndentation:
  EnforcedStyle: outdent

Layout/ExtraSpacing:
  AllowForAlignment: true

Layout/LineLength:
  Max: 120
  AllowedPatterns:
    - '^# [^\n]+'

Layout/HashAlignment:
  EnforcedColonStyle: key
  EnforcedHashRocketStyle: table

Layout/MultilineMethodCallIndentation:
  EnforcedStyle: indented

Layout/SpaceInLambdaLiteral:
  EnforcedStyle: require_space

# Causes issues with the typical way to define Rails scopes
Lint/AmbiguousBlockAssociation:
  Enabled: false

Metrics/AbcSize:
  Max: 25

Metrics/CyclomaticComplexity:
  Max: 25

Metrics/MethodLength:
  Max: 20
  CountAsOne:
    - array
    - hash
    - heredoc
    - method_call

Metrics/ModuleLength:
  Max: 200
  CountAsOne:
    - array
    - hash
    - heredoc
    - method_call

Metrics/BlockLength:
  Exclude:
    - "lib/tasks/**/*.rake"
    - "spec/**/*"
  CountAsOne:
    - array
    - hash
    - heredoc
    - method_call

Metrics/ClassLength:
  Max: 200
  CountAsOne:
    - array
    - hash
    - heredoc
    - method_call

Naming/PredicatePrefix:
  NamePrefix:
    - is_
    - have_
  ForbiddenPrefixes:
    - is_
    - have_

Naming/RescuedExceptionsVariableName:
  PreferredName: error

RSpec/ExpectChange:
  EnforcedStyle: block

RSpec/ExampleLength:
  CountAsOne:
    - array
    - hash
    - heredoc
    - method_call

RSpec/HookArgument:
  EnforcedStyle: each

RSpec/NestedGroups:
  Max: 5

RSpecRails/InferredSpecType:
  Enabled: false

RSpec/MultipleMemoizedHelpers:
  Enabled: false

RSpecRails/NegationBeValid:
  EnforcedStyle: be_invalid

Style/ConditionalAssignment:
  EnforcedStyle: assign_inside_condition
  IncludeTernaryExpressions: false

Style/AccessorGrouping:
  EnforcedStyle: separated

Style/Documentation:
  Enabled: false

Style/HashSyntax:
  EnforcedShorthandSyntax: always

Style/StringLiterals:
  EnforcedStyle: single_quotes

Style/TrailingCommaInHashLiteral:
  EnforcedStyleForMultiline: consistent_comma

Style/TrailingCommaInArrayLiteral:
  EnforcedStyleForMultiline: consistent_comma
