name: CI

on:
  pull_request:
  push:
    branches: [main]

jobs:
  rubocop:
    name: Rubocop
    runs-on: ubuntu-latest

    strategy:
      matrix:
        ruby:
          - '3.2.9'
          - '3.3.9'
          - '3.4.6'

    steps:
    - uses: actions/checkout@v4
      with:
        persist-credentials: false
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: ${{ matrix.ruby }}
        bundler-cache: true
    - name: Rubocop
      run: bin/rubocop --parallel

  rspec_sqlite:
    name: RSpec (SQLite)
    runs-on: ubuntu-latest

    strategy:
      matrix:
        ruby:
          - '3.2.9'
          - '3.3.9'
          - '3.4.6'

    steps:
      - uses: actions/checkout@v4
        with:
          persist-credentials: false
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
          bundler-cache: true
      - name: RSpec
        run: bin/rspec
        env:
          RAILS_ENV: test
          DATABASE_ADAPTER: sqlite3

  rspec_postgresql:
    name: RSpec (PostgreSQL)
    runs-on: ubuntu-latest
    
    services:
      postgres:
        image: postgres:17.6
        env:
          POSTGRES_USER: soft_deletable
          POSTGRES_PASSWORD: soft_deletable
          POSTGRES_DB: soft_deletable_test
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    strategy:
      matrix:
        ruby:
          - '3.2.9'
          - '3.3.9'
          - '3.4.6'

    steps:
      - uses: actions/checkout@v4
        with:
          persist-credentials: false
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
          bundler-cache: true
      - name: RSpec
        run: bin/rspec
        env:
          RAILS_ENV: test
          DATABASE_ADAPTER: postgresql
          DATABASE: soft_deletable_test
          DATABASE_URL: postgres://soft_deletable:soft_deletable@localhost:5432/soft_deletable_test
